#ifndef DEFINES_H
#define DEFINES_H

#define WINDOW_HEIGHT 800
#define WINDOW_WIDTH 800

#define SHIP_HEIGHT 70
#define SHIP_WIDTH 70

#define BLASTER_HEIGHT 20
#define BLASTER_WIDTH 50

#define ENEMY_ONE_HEIGHT 45
#define ENEMY_ONE_WIDTH 50

#define SHIP_SPEED 4
#define BLASTER_SPEED 5
#define ENEMY_BLASTER_SPEED 2
#define ENEMY_ONE_SPEED 1
#define GAME_SPEED 2

#define DEBUG 1

#endif // DEFINES_H
